### DISCUSSION TITLE
Does this have support for anchor tag linking to sections of the PDF, and therefore ToC abilities?

### DISCUSSION THREAD

**Discussion by byOskar** [spatie/laravel-pdf#16] [Q&A]
I currently use another PDF generating library (typeset.sh) and it allows the above, but it's just a bit clunky. Would something like this work?

```css
#toc > li  > a::after {
    content: 'Page '
    target-counter(attr(href url), page);
}
```
