### DISCUSSION TITLE
Laravel Sail instructions

### DISCUSSION THREAD

**Discussion by piotrjoniec** [spatie/laravel-pdf#90] [General]
If anyone is trying to get it to work with Laravel Sail, this is what worked for me.

First, make sure to publish the Sail Dockerfile:
```
sail artisan sail:publish
```
Add this at the end of your Dockerfile (before `EXPOSE 8000`):
```Dockerfile

RUN npx puppeteer browsers install chrome \
    && mkdir /home/sail/.cache \
    && mv /root/.cache/puppeteer /home/sail/.cache \
    && apt-get update \
    && apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 \
    libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 \
    libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 \
    libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
```

Rebuild the containers:
```
sail build
```

**Comment by ArielMejiaDev** [comment]
@piotrjoniec this should be added to the `Dockerfile` right?

**Reply by piotrjoniec** [reply]
@ArielMejiaDev You're right. I've updated the OP with correct instructions.

**Comment by bru95** [comment]
Hi guys!
I follow the @piotrjoniec instruction's but I keep getting the error.
Can someone help me?
![Captura de Tela 2024-12-16 às 17 47 11](https://github.com/user-attachments/assets/a7499639-b4c8-468a-9a17-4b5d20bf70f1)

**Comment by bru95** [comment]
I found the complete solution:

https://laracasts.com/discuss/channels/laravel/run-browsershot-in-laravel-sail-on-arm64-mac

**Reply by mahjoubkzbr** [reply]
> I found the complete solution:
> 
> https://laracasts.com/discuss/channels/laravel/run-browsershot-in-laravel-sail-on-arm64-mac

Hey there, what config is OP referring to when stating "Adapting the browsershot config to add chromium host configuration."?

Thanks in advance

**Comment by nickpoulos** [comment]
This all seems extra complicated? This has been working for me: 

Add chromium as a new service within your docker-compose.yml -- make sure to update the volume and network names to match your app instead of "myapp". 

```yaml
    chromium:
        image: zenika/alpine-chrome
        command:
            - chromium-browser
            - '--headless'
            - '--disable-gpu'
            - '--remote-debugging-address=0.0.0.0'
            - '--remote-debugging-port=9222'
        cap_add:
            - SYS_ADMIN
        volumes:
            - 'myapp-chromium:/tmp/chromium'
        networks:
            - myapp
networks:
    myapp:
        driver: bridge
volumes:
    myapp-chromium:
        driver: local
```

Then your main laravel.test service, make sure to give access to your chromium volume, and access to the same network.  Update your depends_on as well to include chromium.

```yaml
        volumes:
            - 'myapp-chromium:/tmp/chromium'
            - './src:/var/www/'
        networks:
            - myapp
        depends_on:
            - redis
            - mailpit
            - minio
            - selenium
            - chromium
```

Instead of hardcoding IPs, you can do this inside your config/browsershot.php: 

```php
<?php

return [
    'chromium' => [
        'host_ip' => gethostbyname(env('BROWSER_SHOT_CHROMIUM_HOSTNAME')),
    ],
];

```

Add this in your .env

```env
BROWSER_SHOT_CHROMIUM_HOSTNAME=chromium
```

Finally, you can use BrowserShot facade like so: 

```php
        $browser = Browsershot::url($url)
                                ->setRemoteInstance(config('browsershot.chromium.host_ip'))
```


This has been working for me without needing to rebuild the main containers, and use hardcoded IPs.
