### ISSUE TITLE
[Bug]: TailwindCSS (likely js) is not working without including it as a script

### ISSUE THREAD

**Issue by Helfull** [spatie/laravel-pdf#242]
### What happened?

I tried to convert my ticket page to a PDF, it did not include the styles from the HTML, i even tried to use `Blade::render` and did sanity check if the CSS and JS are included.

After adding `<script src="https://cdn.tailwindcss.com"></script>` it does display with the default tailwind css theme.

### How to reproduce the bug

If i include my assets `@vite(['resources/css/app.css', 'resources/js/app.js'])` i want to have my JS and CSS be included in the final pdf styles so it represents my HTML/CSS.

```php
Pdf::view('tickets::pdfs.ticket', ['ticket' => '123'])
    ->withBrowsershot(function (Browsershot $browsershot) {
        return $browsershot
            ->setNodeBinary(config('browsershot.NODE'))
            ->setNpmBinary(config('browsershot.NPM'))
            ->setRemoteInstance(config('browsershot.chromium.host'))
            ->ignoreHttpsErrors();
    })
    ->format(Format::A4)
    ->save('ticket.pdf');
```

config:
```php
<?php

declare(strict_types=1);

return [
    'PATH_CHROME' => env('PATH_CHROME'),
    'PATH_NODE_MODULES' => env('PATH_NODE_MODULES'),
    'NODE' => env('NODE', '/usr/bin/node'),
    'NPM' => env('NPM', '/usr/bin/npm'),

    'chromium' => [
        'host' => env('BROWSERSHOT_CHROMIUM_HOST', '172.22.0.100'),
    ],
];
```

### Package Version

1.5.5

### PHP Version

8.3

### Laravel Version

12.1.1

### Notes

Running on WSL2 with docker

In my docker-compose i added

```yaml
...

    chromium:
        image: zenika/alpine-chrome
        command:
          [
              chromium-browser,
              "--headless",
              "--disable-gpu",
              "--remote-debugging-address=0.0.0.0",
              "--remote-debugging-port=9222",
          ]
        cap_add:
            - SYS_ADMIN
        volumes:
            - tmpfiles:/tmp
        ports:
            - "9222:9222"
        networks:
            sail:
                ipv4_address: 172.22.0.100
networks:
    sail:
        ipam:
            driver: default
            config:
                -   subnet: "172.22.0.0/24"
volumes:
    tmpfiles:
        driver: local
    sail-mysql:
        driver: local
...
```
